## 順伝播
このファイルでは順伝播(forward)処理のみを実装したレイヤ, モデルを用いて, 入力に対してなんらかの値を出力する.  
今回用いるモデル(TwoLayerNet)は2層の中間層を持ち,  
入力(2チャネル)->中間層(4チャネル)->出力層(3チャネル)  
という流れで推移する

In [1]:
import numpy as np
import forward_net

In [2]:
# input data
x = np.random.randn(10, 2)

# model
model = forward_net.TwoLayerNet(2, 4, 3)
pb = model.forward(x)
print(pb)

[[-0.4471146   0.19369535  1.9416608 ]
 [-1.52124403 -0.28335951  1.95659822]
 [-2.86318726 -1.09384889  2.34849651]
 [-1.72373984 -0.18476351  1.82161275]
 [-2.27243738 -0.93815617  2.27242125]
 [-1.12835806 -0.06801017  1.90322759]
 [-1.71305285 -0.47604595  2.0485517 ]
 [ 0.01406805  0.32384305  2.20261328]
 [ 0.1317886   0.40858767  2.21068293]
 [-1.71179691 -0.39766238  1.99823159]]
